name: my_dbt_project
version: 1.0.0
config-version: 2

# Specify the profile name from profiles.yml
profile: 'default'

# Directory where dbt will look for models (adjust as per your project structure)
source-paths: ["models"]

# Directory where compiled SQL files will be stored
target-path: "target"

# List of models and their configurations
models:
  finance_domain:
    schema: finance_sch  # Schema for finance domain
    enabled: true

  sales_domain:
    schema: sales_sch  # Schema for sales domain
    enabled: true

  customer_domain:
    schema: customer_sch  # Schema for customer domain
    enabled: true

# Additional configurations as needed
